POST='POST'
GET='GET'
PUT='PUT'
DELETE='DELETE'

REGISTER='/register'
LOGIN='/login'
CREATE_ACCOUNT='/create_account'
VIEW_ACCOUNTS='/view_accounts'
CREATE_TRANSACTION='/create_transaction'
VIEW_TRANSACTION='/view_transaction'